gha: drop google-github-actions/setup-gcloud
Dropping as it is unused right now anyway.

```
Run google-github-actions/setup-gcloud@master
/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/c7a78187-5f32-485e-8f7c-e46f075bfada -f /home/runner/work/_temp/748eb92c-161d-470a-b11f-9ffdcfe2be03
Successfully set default project
Warning: "service_account_key" has been deprecated. Please switch to using google-github-actions/auth which supports both Workload Identity Federation and Service Account Key JSON authentication. For more details, see https://github.com/google-github-actions/setup-gcloud#authorization
Error: google-github-actions/setup-gcloud failed with: The process '/opt/hostedtoolcache/gcloud/365.0.1/x64/bin/gcloud' failed with exit code 1
```